### ISSUE TITLE
Pagina de cadastro de produto

### ISSUE THREAD

**Issue by arthursakemi** [arthursakemi/pi4-holandes-voador-webstore-frontend#2]
- [x] Formulário de cadastro de produtos
  -Nome
  -Marca
  -Descrição
  -Preço
  -Estoque
  -Imagens

**Comment by mablds** [comment]
Formulário criado. Já estamos selecionando as imagens no front mas estamos descobrindo como fazer o upload para o Spring via HTTP.

**Comment by mablds** [comment]
Issue reaberta. Fechada por engano.

**Comment by mablds** [comment]
Para salvar as imagens no MySQL, usaremos o exemplo encontrado no stackoverflow:

https://stackoverflow.com/questions/41369055/how-to-go-about-saving-an-image-in-blob-format-to-mysql-in-java
